### ISSUE TITLE
SSL CA bundle error

### ISSUE THREAD

**Issue by minecrafter** [navarr/MinecraftProfile#12]
```
>>> $profile = Profile::fromUuid('652a2bc4e8cd405db7b698156ee2dc09');
InvalidArgumentException with message 'SSL CA bundle not found: /Users/andrew/PhpstormProjects/REMOVED/vendor/navarr/minecraft-profile/src/Profile/../../data/cacert.pem'
```

This was within the context of a Laravel 5.4 project, but the issue seems independent of that.

**Comment by navarr** [comment]
Thanks for the report!

Can you verify the existence of a `data` directory inside `vendor/navarr/minecraft-profile`?

I have a good idea of what's causing this.

**Comment by minecrafter** [comment]
Nope:

```
Andrews-Mac-mini:test andrew$ ls -lh vendor/navarr/minecraft-profile/
total 16
-rw-r--r--  1 andrew  staff   541B Aug  6  2016 README.md
-rw-r--r--  1 andrew  staff   650B Aug  6  2016 composer.json
drwxr-xr-x  4 andrew  staff   136B Aug  6  2016 src
```

**Comment by navarr** [comment]
I've just published v1.2.4.

Please update and confirm this resolves the issue.

It was a silly mistake on my part.

**Comment by minecrafter** [comment]
Issue is resolved. 👍

**Comment by navarr** [comment]
Thanks for all your help - sorry about that :)

Surprised it wasn't caught earlier - guessing nobody uses this @.@;

**Comment by minecrafter** [comment]
I do when I'm working with PHP and need information from the Mojang API. That combination is rather rare, but this is what I use when I do have both requirements.
